//! Parser-based HTML sanitization and text normalization.

use std::borrow::Cow;
use std::collections::HashSet;

use ammonia::Builder;
use kuchikiki::{parse_html, traits::TendrilSink, NodeRef};

use crate::document_uploads::parsed::is_reader_asset_file_name;

/// Sanitize an untrusted HTML document and retain only reader-safe metadata.
///
/// Ammonia is the security boundary: it parses browser-style HTML, allowlists
/// elements/attributes, and validates decoded URL schemes. Rebuilding the outer
/// document keeps title/language/direction metadata without retaining an
/// untrusted head, stylesheet, or document-level attribute.
pub(crate) fn sanitize_html(html: &str) -> String {
    let document = parse_html().one(html).document_node;
    let title = selected_text(&document, "title");
    let root_language = selected_attribute(&document, "html", "lang").and_then(valid_language);
    let root_direction = selected_attribute(&document, "html", "dir").and_then(valid_direction);
    let body_language = selected_attribute(&document, "body", "lang").and_then(valid_language);
    let body_direction = selected_attribute(&document, "body", "dir").and_then(valid_direction);
    let body = document
        .select_first("body")
        .ok()
        .map(|node| node.as_node().clone())
        .unwrap_or_else(|| document.clone());

    let mut builder = Builder::default();
    builder
        .add_tags(&["main", "section"])
        .add_generic_attributes(&["dir", "id", "name", "data-papercut-section"])
        .add_tag_attributes("img", &["data-papercut-asset", "loading", "decoding"])
        .add_allowed_classes("section", &["epub-chapter"])
        .url_schemes(HashSet::from(["data", "http", "https", "mailto", "tel"]))
        .attribute_filter(filter_reader_attribute);
    let safe_body = builder.clean(&serialize_children(&body)).to_string();

    let mut safe = String::from("<!doctype html><html");
    push_document_attributes(
        &mut safe,
        root_language.as_deref(),
        root_direction.as_deref(),
    );
    safe.push_str("><head>");
    if let Some(title) = title.filter(|title| !title.is_empty()) {
        safe.push_str("<title>");
        safe.push_str(&escape_html_text(&title));
        safe.push_str("</title>");
    }
    safe.push_str("</head><body");
    push_document_attributes(
        &mut safe,
        body_language.as_deref(),
        body_direction.as_deref(),
    );
    safe.push('>');
    safe.push_str(&safe_body);
    safe.push_str("</body></html>");
    safe
}

/// Keep only URLs that the app reader knows how to handle.
///
/// Ammonia validates decoded schemes before this callback. The extra policy
/// rejects cross-file relative links and remote images while retaining local
/// footnotes and the bounded raster data URLs generated by the EPUB importer.
fn filter_reader_attribute<'a>(
    element: &str,
    attribute: &str,
    value: &'a str,
) -> Option<Cow<'a, str>> {
    match (element, attribute) {
        (_, "data-papercut-section") if is_section_ordinal(value) => Some(Cow::Borrowed(value)),
        (_, "data-papercut-section") => None,
        ("a", "href") if is_reader_href(value) => Some(Cow::Borrowed(value)),
        ("a", "href") => None,
        ("img", "src") if is_safe_raster_data_url(value) => Some(Cow::Borrowed(value)),
        ("img", "src") => None,
        ("img", "data-papercut-asset") if is_reader_asset_file_name(value) => {
            Some(Cow::Borrowed(value))
        }
        ("img", "data-papercut-asset") => None,
        ("img", "loading") if value == "lazy" => Some(Cow::Borrowed(value)),
        ("img", "loading") => None,
        ("img", "decoding") if value == "async" => Some(Cow::Borrowed(value)),
        ("img", "decoding") => None,
        (_, _) if value.trim_start().to_ascii_lowercase().starts_with("data:") => None,
        _ => Some(Cow::Borrowed(value)),
    }
}

fn is_section_ordinal(value: &str) -> bool {
    value
        .parse::<usize>()
        .is_ok_and(|ordinal| value == ordinal.to_string())
}

fn is_reader_href(value: &str) -> bool {
    let lower = value.trim().to_ascii_lowercase();
    lower.starts_with('#')
        || lower.starts_with("http://")
        || lower.starts_with("https://")
        || lower.starts_with("mailto:")
        || lower.starts_with("tel:")
}

fn is_safe_raster_data_url(value: &str) -> bool {
    let lower = value.trim().to_ascii_lowercase();
    [
        "data:image/png;base64,",
        "data:image/jpeg;base64,",
        "data:image/gif;base64,",
        "data:image/webp;base64,",
    ]
    .iter()
    .any(|prefix| lower.starts_with(prefix))
}

fn selected_text(document: &NodeRef, selector: &str) -> Option<String> {
    document
        .select_first(selector)
        .ok()
        .map(|node| normalize_text(&node.text_contents()))
}

/// Read a local-name attribute regardless of whether parsed XHTML namespaced it.
fn selected_attribute(document: &NodeRef, selector: &str, attribute: &str) -> Option<String> {
    let node = document.select_first(selector).ok()?;
    let attributes = node.attributes.borrow();
    attributes
        .map
        .iter()
        .find(|(name, _)| name.local.as_ref().eq_ignore_ascii_case(attribute))
        .map(|(_, value)| value.value.to_string())
}

fn valid_language(value: String) -> Option<String> {
    let value = value.trim();
    (value.len() <= 64
        && !value.is_empty()
        && value
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '-'))
    .then(|| value.to_string())
}

fn valid_direction(value: String) -> Option<String> {
    let value = value.trim().to_ascii_lowercase();
    matches!(value.as_str(), "ltr" | "rtl" | "auto").then_some(value)
}

fn push_document_attributes(html: &mut String, language: Option<&str>, direction: Option<&str>) {
    if let Some(language) = language {
        html.push_str(" lang=\"");
        html.push_str(language);
        html.push('"');
    }
    if let Some(direction) = direction {
        html.push_str(" dir=\"");
        html.push_str(direction);
        html.push('"');
    }
}

fn escape_html_text(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn serialize_children(node: &NodeRef) -> String {
    let mut bytes = Vec::new();
    for child in node.children() {
        if child.serialize(&mut bytes).is_err() {
            return String::new();
        }
    }
    String::from_utf8(bytes).unwrap_or_default()
}

/// Strip all tags to plain text and decode entities.
///
/// Inline markup must not become a word boundary: many EPUBs style drop caps or
/// emphasis as adjacent inline tags, e.g. `<b>C</b><b>ORNELIA</b>`, and the FTS
/// index needs to see the same word a reader sees. Block-like tags still add a
/// separator so neighboring paragraphs do not collapse together.
pub(crate) fn strip_tags(html: &str) -> String {
    let mut out = String::with_capacity(html.len());
    let mut pos = 0usize;

    while let Some(start_rel) = html[pos..].find('<') {
        let start = pos + start_rel;
        out.push_str(&html[pos..start]);

        let Some(end_rel) = html[start..].find('>') else {
            pos = html.len();
            break;
        };
        let end = start + end_rel;
        if tag_separates_text(&html[start + 1..end]) {
            out.push(' ');
        }
        pos = end + 1;
    }

    out.push_str(&html[pos..]);
    decode_entities(&out)
}

/// Decide whether removing a tag should leave a word boundary in indexed text.
///
/// The list is intentionally a small block/row/line-break set. Inline tags like
/// `b`, `i`, `span`, and `a` are omitted so styled words remain searchable as
/// the continuous text users see.
fn tag_separates_text(tag: &str) -> bool {
    matches!(
        tag_name(tag).as_str(),
        "address"
            | "article"
            | "aside"
            | "blockquote"
            | "br"
            | "caption"
            | "dd"
            | "div"
            | "dl"
            | "dt"
            | "figcaption"
            | "figure"
            | "footer"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "header"
            | "hr"
            | "li"
            | "main"
            | "nav"
            | "ol"
            | "p"
            | "pre"
            | "section"
            | "td"
            | "th"
            | "tr"
            | "ul"
    )
}

/// Pull the element name out of a raw tag body from the lightweight text scanner.
fn tag_name(tag: &str) -> String {
    tag.trim()
        .trim_start_matches('/')
        .split_whitespace()
        .next()
        .unwrap_or("")
        .trim_end_matches('/')
        .to_ascii_lowercase()
}

/// Decode the small set of HTML entities that appear in extracted text.
pub(crate) fn decode_entities(text: &str) -> String {
    text.replace("&nbsp;", " ")
        .replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
}

/// Collapse all runs of whitespace into single spaces and trim the result.
pub(crate) fn normalize_text(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn removes_active_content_and_decoded_script_urls() {
        let html = r##"
            <html><body onload="alert(1)">
              <script>alert(1)</script><style>body{display:none}</style>
              <a href="java&#x73;cript:alert(2)" onclick="alert(3)">Unsafe</a>
              <a href="#note-1">Footnote</a><p id="note-1" style="color:red">Safe</p>
            </body></html>
        "##;
        let sanitized = sanitize_html(html);

        assert!(!sanitized.contains("alert("));
        assert!(!sanitized.contains("style="));
        assert!(!sanitized.contains("javascript:"));
        assert!(sanitized.contains(r##"href="#note-1""##));
        assert!(sanitized.contains(r#"id="note-1""#));
    }

    #[test]
    fn keeps_only_generated_raster_images() {
        let asset_name = format!("image-{}.png", "a".repeat(64));
        let sanitized = sanitize_html(&format!(
            r#"<body>
                <img src="https://example.com/track.png" alt="Remote">
                <img src="data:image/svg+xml;base64,PHN2Zz4=" alt="SVG">
                <img src="data:image/png;base64,iVBORw0KGgo=" alt="Cover">
                <img data-papercut-asset="{asset_name}" loading="lazy" decoding="async" alt="Stored">
                <img data-papercut-asset="../source.html" alt="Unsafe">
            </body>"#
        ));

        assert!(!sanitized.contains("https://example.com/track.png"));
        assert!(!sanitized.contains("image/svg+xml"));
        assert!(sanitized.contains("data:image/png;base64,iVBORw0KGgo="));
        assert!(sanitized.contains(&asset_name));
        assert!(sanitized.contains("loading=\"lazy\""));
        assert!(!sanitized.contains("../source.html"));
    }

    #[test]
    fn keeps_only_canonical_section_ordinals() {
        let sanitized = sanitize_html(
            r#"<body>
                <p data-papercut-section="7">Safe</p>
                <p data-papercut-section="07">Noncanonical</p>
                <p data-papercut-section="-1">Negative</p>
            </body>"#,
        );

        assert!(sanitized.contains(r#"data-papercut-section="7""#));
        assert_eq!(sanitized.matches("data-papercut-section=").count(), 1);
    }

    #[test]
    fn strip_tags_keeps_adjacent_inline_text_together() {
        let text = normalize_text(&strip_tags(
            "<div><b>C</b><b>ORNELIA</b> had <i>always</i> loved Saturnalia.</div>",
        ));

        assert_eq!(text, "CORNELIA had always loved Saturnalia.");
    }

    #[test]
    fn strip_tags_separates_blocks_and_line_breaks() {
        let text = normalize_text(&strip_tags("<p>First</p><p>Second<br/>line</p>"));

        assert_eq!(text, "First Second line");
    }

    #[test]
    fn keeps_title_language_direction_and_epub_chapters() {
        let sanitized = sanitize_html(
            r#"<html lang="ar" dir="rtl"><head><title>عنوان آمن</title></head>
               <body lang="ar-SA"><section class="epub-chapter" id="chapter-1">نص آمن</section></body></html>"#,
        );

        assert!(sanitized.contains(r#"<html lang="ar" dir="rtl">"#));
        assert!(sanitized.contains("<title>عنوان آمن</title>"));
        assert!(sanitized.contains(r#"<body lang="ar-SA">"#));
        assert!(sanitized.contains(r#"class="epub-chapter""#));
        assert!(sanitized.contains(r#"id="chapter-1""#));
    }
}
