import { useCallback, useRef, useState } from 'react'
import i18n from '../../i18n'
import {
  cancelNativeAudiobookSave,
  getNativeAudiobookStatus,
  getNativeTtsCapabilities,
  listenNativeAudiobookSaveProgress,
  saveNativeAudiobook,
  type NativeAudiobookSaveProgress,
} from '../api/nativeTts'
import { logTtsDiagnostic, summarizeTtsCapabilities } from '../diagnostics/TtsDiagnostics'
import {
  resolveTtsDtype,
  type TtsOptions,
  type TtsChunk,
} from '../types'

type AudiobookSaveStatus = 'idle' | 'checking' | 'partial' | 'saving' | 'saved' | 'error'

export interface AudiobookCacheState {
  status: AudiobookSaveStatus
  message: string
  cachedChunks: number
  totalChunks: number
  complete: boolean
  audioDurationSec: number
  wavBytes: number
  appliedThreadCount: number | null
}

const INITIAL_STATE: AudiobookCacheState = {
  status: 'idle',
  message: '',
  cachedChunks: 0,
  totalChunks: 0,
  complete: false,
  audioDurationSec: 0,
  wavBytes: 0,
  appliedThreadCount: null,
}
// Used in two modes: a lightweight status checker for the open document, and
// a long-running native save job that writes every missing chunk directly to
// app data. Playback is saved-only; missing chunks are generated by Save, not Play.
export function useAudiobookCache() {
  const [state, setState] = useState<AudiobookCacheState>(INITIAL_STATE)
  const jobIdRef = useRef(0)
  const activeNativeJobIdRef = useRef<string | null>(null)
  const checkIdRef = useRef(0)
  const saveStartedAtRef = useRef(0)

  const reset = useCallback(() => {
    checkIdRef.current += 1
    jobIdRef.current += 1
    activeNativeJobIdRef.current = null
    setState(INITIAL_STATE)
  }, [])

  const check = useCallback((chunks: TtsChunk[], options: TtsOptions) => {
    const checkId = checkIdRef.current + 1
    checkIdRef.current = checkId
    const totalChunks = chunks.filter((chunk) => chunk.text.trim()).length
    setState((prev) => ({
      ...prev,
      status: 'checking',
      message: i18n.t('tts.status.checkingSaved'),
      totalChunks,
      cachedChunks: 0,
      complete: false,
      audioDurationSec: 0,
      wavBytes: 0,
      appliedThreadCount: null,
    }))

    void (async () => {
      try {
        if (!options.documentUrl) throw new Error('Saved audiobook status requires a document URL')
        const status = await getNativeAudiobookStatus(options.documentUrl, chunks, options)
        if (checkIdRef.current !== checkId) return
        setState({
          status: status.complete ? 'saved' : 'partial',
          message: status.complete ? i18n.t('tts.status.saved') : i18n.t('tts.status.notSaved'),
          cachedChunks: status.cachedChunks,
          totalChunks: status.totalChunks,
          complete: status.complete,
          audioDurationSec: status.audioDurationSec,
          wavBytes: status.wavBytes,
          appliedThreadCount: null,
        })
      } catch (err) {
        if (checkIdRef.current !== checkId) return
        setState({
          status: 'error',
          message: err instanceof Error ? err.message : String(err),
          cachedChunks: 0,
          totalChunks,
          complete: false,
          audioDurationSec: 0,
          wavBytes: 0,
          appliedThreadCount: null,
        })
      }
    })()
  }, [])

  const save = useCallback((chunks: TtsChunk[], options: TtsOptions) => {
    const speakableChunks = chunks.filter((chunk) => chunk.text.trim())
    if (speakableChunks.length === 0) return

    const jobId = jobIdRef.current + 1
    const nativeJobId = 'tts-save-' + Date.now() + '-' + jobId
    jobIdRef.current = jobId
    activeNativeJobIdRef.current = nativeJobId
    checkIdRef.current += 1
    saveStartedAtRef.current = performance.now()

    setState({
      status: 'checking',
      message: i18n.t('tts.status.checkingNativeAndSaved'),
      cachedChunks: 0,
      totalChunks: speakableChunks.length,
      complete: false,
      audioDurationSec: 0,
      wavBytes: 0,
      appliedThreadCount: null,
    })

    void (async () => {
      let unlisten: (() => void) | null = null
      try {
        const capabilities = await getNativeTtsCapabilities()
        logTtsDiagnostic('[tts-native] capabilities', summarizeTtsCapabilities(capabilities))
        if (!capabilities.available) throw new Error(capabilities.reason)
        if (!options.documentUrl) throw new Error('Native audiobook save requires a document URL')
        if (jobIdRef.current !== jobId) return

        unlisten = await listenNativeAudiobookSaveProgress((progress) => {
          if (progress.jobId !== nativeJobId || jobIdRef.current !== jobId) return
          handleNativeProgress(progress, options)
        })

        const result = await saveNativeAudiobook({
          jobId: nativeJobId,
          documentUrl: options.documentUrl,
          title: options.title ?? i18n.t('tts.audiobooks.defaultTitle'),
          chunks: speakableChunks,
          options,
        })
        if (jobIdRef.current !== jobId) return

        logTtsDiagnostic('[tts-save] completed', {
          totalMs: Math.round(performance.now() - saveStartedAtRef.current),
          generatedChunks: result.generatedChunks,
          totalChunks: result.totalChunks,
          generateMs: result.generateMs,
          audioDurationSec: Number(result.audioDurationSec.toFixed(2)),
          wavBytes: result.wavBytes,
          realTimeFactor: Number(realTimeFactor(result.generateMs, result.audioDurationSec).toFixed(2)),
          dtype: resolveTtsDtype(options),
          actualDevice: 'native',
          preferredDevice: 'native',
          backend: result.backend,
          dir: result.dir,
          threadCount: options.threadCount,
          appliedThreadCount: result.appliedThreadCount,
        })

        setState({
          status: 'saved',
          message: i18n.t('tts.status.saved'),
          cachedChunks: result.cachedChunks,
          totalChunks: result.totalChunks,
          complete: result.complete,
          audioDurationSec: result.audioDurationSec,
          wavBytes: result.wavBytes,
          appliedThreadCount: result.appliedThreadCount,
        })
      } catch (err) {
        if (jobIdRef.current !== jobId) return
        logTtsDiagnostic('[tts-save] failed', {
          totalMs: Math.round(performance.now() - saveStartedAtRef.current),
          dtype: resolveTtsDtype(options),
          threadCount: options.threadCount,
          error: err instanceof Error ? err.message : String(err),
        }, 'error')
        setState({
          status: 'error',
          message: err instanceof Error ? err.message : String(err),
          cachedChunks: 0,
          totalChunks: speakableChunks.length,
          complete: false,
          audioDurationSec: 0,
          wavBytes: 0,
          appliedThreadCount: null,
        })
      } finally {
        unlisten?.()
        if (activeNativeJobIdRef.current === nativeJobId) activeNativeJobIdRef.current = null
      }
    })()
  }, [])

  const cancel = useCallback(() => {
    const nativeJobId = activeNativeJobIdRef.current
    if (nativeJobId) void cancelNativeAudiobookSave(nativeJobId)
    activeNativeJobIdRef.current = null
    jobIdRef.current += 1
    setState((prev) => ({
      ...prev,
      status: prev.cachedChunks === prev.totalChunks && prev.totalChunks > 0 ? 'saved' : 'partial',
      complete: prev.cachedChunks === prev.totalChunks && prev.totalChunks > 0,
      message: i18n.t('tts.status.saveCancelled'),
    }))
  }, [])

  return {
    state,
    check,
    save,
    cancel,
    reset,
  }

  function handleNativeProgress(progress: NativeAudiobookSaveProgress, options: TtsOptions): void {
    const status: AudiobookSaveStatus = progress.status === 'saved'
      ? 'saved'
      : progress.status === 'checking'
        ? 'checking'
        : 'saving'

    if (progress.status === 'saving' && progress.chunkNumber && !progress.generateMs) {
      logTtsDiagnostic('[tts-save] native chunk start', {
        chunkNumber: progress.chunkNumber,
        chunkId: progress.chunkId,
        textChars: progress.textChars,
        textPreview: progress.textPreview,
        cachedChunks: progress.cachedChunks,
        totalChunks: progress.totalChunks,
        backend: progress.backend,
        dtype: resolveTtsDtype(options),
        threadCount: options.threadCount,
        silmaNfeStep: options.silmaNfeStep,
        appliedThreadCount: progress.appliedThreadCount,
      })
    }

    if (progress.status === 'saving' && progress.generateMs) {
      logTtsDiagnostic('[tts-save] native chunk', {
        chunkNumber: progress.chunkNumber,
        chunkId: progress.chunkId,
        textChars: progress.textChars,
        textPreview: progress.textPreview,
        generateMs: progress.generateMs,
        preprocessMs: progress.preprocessMs ?? 0,
        synthesisMs: progress.synthesisMs ?? 0,
        writeMs: progress.writeMs ?? 0,
        validateMs: progress.validateMs ?? 0,
        synthesisTextChars: progress.synthesisTextChars ?? 0,
        audioDurationSec: progress.audioDurationSec ? Number(progress.audioDurationSec.toFixed(2)) : 0,
        realTimeFactor: progress.audioDurationSec && progress.audioDurationSec > 0
          ? Number((progress.generateMs / 1000 / progress.audioDurationSec).toFixed(2))
          : 0,
        wavBytes: progress.wavBytes,
        backend: progress.backend,
        dtype: resolveTtsDtype(options),
        threadCount: options.threadCount,
        silmaNfeStep: options.silmaNfeStep,
        appliedThreadCount: progress.appliedThreadCount,
      })
    }

    if (progress.status === 'saved' && progress.generateMs) {
      const generatedAudioDurationSec = progress.audioDurationSec ?? 0
      logTtsDiagnostic('[tts-save] native performance summary', {
        generatedChunks: progress.generatedChunks,
        totalChunks: progress.totalChunks,
        generateMs: progress.generateMs,
        preprocessMs: progress.preprocessMs ?? 0,
        synthesisMs: progress.synthesisMs ?? 0,
        writeMs: progress.writeMs ?? 0,
        validateMs: progress.validateMs ?? 0,
        indexingMs: progress.indexingMs ?? 0,
        totalSourceChars: progress.totalSourceChars ?? 0,
        totalSynthesisChars: progress.totalSynthesisChars ?? 0,
        audioDurationSec: Number(generatedAudioDurationSec.toFixed(2)),
        totalAudioDurationSec: Number(progress.totalAudioDurationSec.toFixed(2)),
        realTimeFactor: generatedAudioDurationSec > 0
          ? Number((progress.generateMs / 1000 / generatedAudioDurationSec).toFixed(2))
          : 0,
        wavBytes: progress.wavBytes ?? 0,
        totalWavBytes: progress.totalWavBytes,
        backend: progress.backend,
        dtype: resolveTtsDtype(options),
        threadCount: options.threadCount,
        silmaNfeStep: options.silmaNfeStep,
        appliedThreadCount: progress.appliedThreadCount,
      })
    }

    setState({
      status,
      message: formatNativeProgressMessage(progress),
      cachedChunks: progress.cachedChunks,
      totalChunks: progress.totalChunks,
      complete: progress.status === 'saved' || (
        progress.totalChunks > 0 && progress.cachedChunks === progress.totalChunks
      ),
      audioDurationSec: progress.totalAudioDurationSec,
      wavBytes: progress.totalWavBytes,
      appliedThreadCount: progress.appliedThreadCount,
    })
  }
}

function formatNativeProgressMessage(progress: NativeAudiobookSaveProgress): string {
  if (progress.status === 'checking') return i18n.t('tts.status.checkingCache')
  if (progress.status === 'saved') return i18n.t('tts.status.saved')
  if (progress.chunkNumber) {
    return i18n.t(progress.generateMs ? 'tts.status.savedChunk' : 'tts.status.savingChunk', {
      current: progress.chunkNumber,
      total: progress.totalChunks,
    })
  }
  return progress.message
}

function realTimeFactor(generateMs: number, audioDurationSec: number): number {
  return audioDurationSec > 0 ? generateMs / 1000 / audioDurationSec : 0
}
